#
# modified 2021-06-28
#

env:
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  # Spread additional padding evenly around the terminal content.
  padding:
    x: 10
    y: 10
  # Open in full screen
  startup_mode: Windowed
  decorations: full
  dimensions:
    columns: 85
    lines: 25
# Background opacity here

# Import theme here
import:
  - ~/alacritty/monokai-pro-alacritty.yaml
cursor:
  # Block Underline or Beam
  style: Block

font:
  size: 10
  offset:
    x: 0
    y: 0

mouse:
  hide_when_typing: false
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true
live_config_reload: true
