#!/bin/bash
## Usage: backup.sh [number of nodes] [mode]
## EDIT: rsyncignore

BASE_NAME="node"
DOMAIN=".local"
START_NUM=0
END_NUM=${1:-4}
MODE=${2:-backup}
USER=$(whoami)
REMOTE_PATH="$HOME/arch"
LOCAL_PATH="$HOME/"

if [[ "$MODE" == "restore" ]]; then
    REMOTE_DEST="${USER}@${BASE_NAME}${START_NUM}${DOMAIN}:${REMOTE_PATH}"

    rsync -aAXHvr --verbose --filter="merge $HOME/.config/rsyncignore" -e ssh "$REMOTE_DEST" "$LOCAL_PATH"
    echo "Completed restore"
    exit 0
fi

for ((i=START_NUM; i<=END_NUM; i++)); do
    HOST="${BASE_NAME}$(printf "%02d" $i)${DOMAIN}"
    REMOTE_DEST="${USER}@${HOST}:${REMOTE_PATH}"

    echo "Doing backup for $HOST..."

    if [[ "$MODE" == "backup" ]]; then
        rsync -aAXHvr --verbose --filter="merge $HOME/.config/rsyncignore" -e ssh "$LOCAL_PATH" "$REMOTE_DEST"
    fi

    if [ ! $? -eq 0 ]; then
        echo "Err while doing backup for $HOST. Skipping..."
        exit 1
    fi

    echo "Completed backup for $HOST"
done
